language: python

os:
  - linux

dist: focal

cache:
  pip: true
  directories: $HOME/.cache/

python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

install:
  - pip install setuptools --upgrade
  - pip install .

script:
  - python -m pytest
