datasets:
  &cifar100_train cifar100/train: !import_call
    _name: &dataset_name 'cifar100'
    _root: &root_dir !join ['~/datasets/', *dataset_name]
    key: 'torchvision.datasets.CIFAR100'
    init:
      kwargs:
        root: *root_dir
        train: True
        download: True
        transform: !import_call
          key: 'torchvision.transforms.Compose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'torchvision.transforms.RandomCrop'
                  init:
                    kwargs:
                      size: 32
                      padding: 4
                - !import_call
                  key: 'torchvision.transforms.RandomHorizontalFlip'
                  init:
                    kwargs:
                      p: 0.5
                - !import_call
                  key: 'torchvision.transforms.ToTensor'
                  init:
                - !import_call
                  key: 'torchvision.transforms.Normalize'
                  init:
                    kwargs: &normalize_kwargs
                      mean: [0.5070754, 0.48655024, 0.44091907]
                      std: [0.26733398, 0.25643876, 0.2761503]
  &cifar100_test cifar100/test: !import_call
    key: 'torchvision.datasets.CIFAR100'
    init:
      kwargs:
        root: *root_dir
        train: False
        download: True
        transform: !import_call
          key: 'torchvision.transforms.Compose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'torchvision.transforms.ToTensor'
                  init:
                - !import_call
                  key: 'torchvision.transforms.Normalize'
                  init:
                    kwargs: *normalize_kwargs

models:
  teacher_model:
    key: &teacher_model_key 'wide_resnet28_10'
    kwargs:
      dropout_p: 0.0
      num_classes: 100
      pretrained: True
    src_ckpt:
  student_model:
    key: &student_model_key 'densenet_bc_k12_depth100'
    kwargs:
      num_classes: 100
      memory_efficient: False
      pretrained: False
    _experiment: &student_experiment !join [*dataset_name, '-', *student_model_key, '_from_', *teacher_model_key]
    src_ckpt:
    dst_ckpt: !join ['./resource/run1.pt']

train:
  log_freq: 100
  num_epochs: 300
  train_data_loader:
    dataset_id: *cifar100_train
    sampler:
      class_or_func: !import_get
        key: 'torch.utils.data.RandomSampler'
      kwargs:
    kwargs:
      batch_size: 64
      num_workers: 16
      pin_memory: True
      drop_last: False
    cache_output:
  val_data_loader:
    dataset_id: *cifar100_test
    sampler: &val_sampler
      class_or_func: !import_get
        key: 'torch.utils.data.SequentialSampler'
      kwargs:
    kwargs:
      batch_size: 128
      num_workers: 16
      pin_memory: True
      drop_last: False
  teacher:
    forward_proc: 'forward_batch_only'
    sequential: []
    wrapper: 'DataParallel'
    requires_grad: False
    frozen_modules: []
  student:
    forward_proc: 'forward_batch_only'
    adaptations:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: True
    frozen_modules: []
  optimizer:
    key: 'SGD'
    kwargs:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    key: 'MultiStepLR'
    kwargs:
      milestones: [150, 225]
      gamma: 0.1
  criterion:
    key: 'WeightedSumLoss'
    kwargs:
      sub_terms:
        kd:
          criterion:
            key: 'KDLoss'
            kwargs:
              student_module_path: '.'
              student_module_io: 'output'
              teacher_module_path: '.'
              teacher_module_io: 'output'
              temperature: 4.0
              alpha: 0.9
              reduction: 'batchmean'
          weight: 1.0

test:
  test_data_loader:
    dataset_id: *cifar100_test
    sampler: *val_sampler
    kwargs:
      batch_size: 1
      num_workers: 16
      pin_memory: True
      drop_last: False
